# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  default:
    cmds:
      - docker compose run --rm app chat

  setup:
    cmds:
      - docker compose run --rm app setup

  doctor:
    cmds:
      - docker compose run --rm app doctor
